### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by max-mapper** [auntbertha/openeligibility#2]
Hiya Erine + team,

First of all I think this is a super great resource. The license at the bottom of http://openeligibility.org/ was CC No Derivatives, have you considered a more liberal license like MIT/BSD (one that allows use in any scenario but clears you of legal responsibility)? In my experience in open source the more strings that you attach to a license the harder it makes it for contributors.

thanks,

max

**Comment by erineg1** [comment]
Hi Max---

Great to hear from you and thanks for the kind words and the reference. We're kind of new to this and are looking for any and all suggestions. So to answer your question, we're open to discussion. But I did want to give you our train of thought.

The first part of openeligibility is to deliver a good and useful taxonomy - which, our thinking was, that it works together best as one piece of work since it's essentially a way of classifying things (which is different from say, a coding project). Our goal was to have a process for suggesting, debating and voting on new categories and sub-categories in an open an transparent way so that it continues to stay one body of work. We'd like to keep it usable and would like to be careful about attempting to make things too confusing (as other taxonomies can be at times).

That said, I hope we can better understand what your requirements might be. Do you see a reason that you'd only want to use a partial taxonomy rather than the whole thing? Or any concerns that we might not be addressing?

Again, appreciate any thoughts, or experiences you may have that may be helpful.

-Erine

**Comment by drapetomaniac** [comment]
One of the issues with CC-ND is it means anyone who wants to use it must use the existing taxonomy as-is.  If there is a desire to add to the taxonomy and you reject that addition and it is needed by that organization, then the user has to abandon this taxonomy altogether.  

It restricts their growth and change entirely to yours.

**Comment by erineg1** [comment]
Thanks guys for the feedback. As mentioned before, I'm not an expert on this stuff but am going to try to read-up on the different licenses, including MIT, as I have time this week. I'll post back here my findings. It's our goal to make this taxonomy as useful as possible - so there's some flexibility. Stay tuned.

**Comment by eric-jahn** [comment]
Creative Commons ShareAlike seems more appropriate than MIT/BSD, since it encourages users to "give back" new taxonomy codes identified, which improves the original taxonomy.
